{
 "title": "Spring Boot - Detail",
 "description": "Shows details for one ore more spring boot applications",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "application", "query": "label_values(application)" },
   {
    "name": "instance",
    "query": "label_values(process_start_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Applications",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "count_values(\"application\", count(process_start_time_seconds{application=~\"$application\", instance=~\"$instance\"}) by (application))",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Istances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "count(process_uptime_seconds{application=~\"$application\", instance=~\"$instance\"}) or (1-absent(process_uptime_seconds{application=~\"$application\", instance=~\"$instance\"}))",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "description": "This panel displays the used memory",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(jvm_memory_used_bytes{application=~\"$application\", instance=~\"$instance\"})",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(jvm_memory_max_bytes{application=~\"$application\", instance=~\"$instance\"})",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(jvm_memory_used_bytes{application=~\"$application\", instance=~\"$instance\"}) / sum(jvm_memory_max_bytes{application=~\"$application\", instance=~\"$instance\"})",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_cpu_usage{application=~\"$application\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(jvm_memory_used_bytes{application=~\"$application\", instance=~\"$instance\"})",
     "legendFormat": "used",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(jvm_memory_committed_bytes{application=~\"$application\", instance=~\"$instance\"})",
     "legendFormat": "commited",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(system_cpu_usage{application=~\"$application\", instance=~\"$instance\"})",
     "legendFormat": "system",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(process_cpu_usage{application=~\"$application\", instance=~\"$instance\"})",
     "legendFormat": "process",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg(avg_over_time(process_cpu_usage{application=~\"$application\", instance=~\"$instance\"}[1h]))",
     "legendFormat": "process-1h",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Instances",
     "type": "table",
     "description": "Displays all instances which are running",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "max(process_start_time_seconds{application=~\"$application\", instance=~\"$instance\"}) by (application, instance) * 1000",
       "legendFormat": "starttime"
      },
      {
       "expr": "max(process_uptime_seconds{application=~\"$application\", instance=~\"$instance\"}) by (application, instance)",
       "legendFormat": "uptime"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{application=~\"$application\", instance=~\"$instance\"}) by (application, instance)",
       "legendFormat": "used memory"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=~\"$application\", instance=~\"$instance\"}) by (application, instance)",
       "legendFormat": "max memjory"
      }
     ]
    },
    {
     "title": "Availability",
     "type": "table",
     "description": "This table displays the availability of an application at a given time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "count(process_uptime_seconds{application=\"$application\", instance=~\"$instance\"}) by (application) or (1-absent(process_uptime_seconds{application=\"$application\", instance=~\"$instance\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "sum(jvm_threads_live_threads{application=~\"$application\", instance=~\"$instance\"}) ",
       "legendFormat": "live",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "sum(jvm_threads_daemon_threads{application=~\"$application\", instance=~\"$instance\"}) ",
       "legendFormat": "deamon",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "sum(jvm_threads_peak_threads{application=~\"$application\", instance=~\"$instance\"})",
       "legendFormat": "peak",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Threads States",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "sum(jvm_threads_states_threads{application=~\"$application\", instance=~\"$instance\"}) by (state)",
       "legendFormat": "{{state}}",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Events",
     "type": "graph",
     "description": "Displays the log events which occured",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "sum by(level) (increase(logback_events_total{application=~\"$application\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{level}}",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Web Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(status) (increase(http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Requests per second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\"}[1m]) ) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Avg Response Time",
     "type": "graph",
     "description": "This panel displays the avg response time",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_sum{application=~\"$application\", instance=~\"$instance\"}) / sum(http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\"})",
       "legendFormat": "time"
      }
     ]
    },
    {
     "title": "Traffic",
     "type": "graph",
     "description": "This panel displays the received and sent bytes",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(tomcat_global_sent_bytes_total{application=~\"$application\", instance=~\"$instance\"})",
       "legendFormat": "send"
      },
      {
       "expr": "sum(tomcat_global_received_bytes_total{application=~\"$application\", instance=~\"$instance\"})",
       "legendFormat": "received"
      }
     ]
    },
    {
     "title": "Top 10 URIs",
     "type": "table",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 22 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "topk(10 ,sum(http_server_requests_seconds_count{application=~\"$application\"}) by(application, uri))",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Hibernate Entities",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "increase(hibernate_entities_loads_total{application_name=\"$application\", application_instanceId=~\"$instance\"}[1m])",
     "legendFormat": "load",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "increase(hibernate_entities_fetches_total{application_name=\"$application\", application_instanceId=~\"$instance\"}[1m])",
     "legendFormat": "fetches",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "increase(hibernate_entities_inserts_total{application_name=\"$application\", application_instanceId=~\"$instance\"}[1m])",
     "legendFormat": "inserts",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "increase(hibernate_entities_updates_total{application_name=\"$application\", application_instanceId=~\"$instance\"}[1m])",
     "legendFormat": "updates",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "increase(hibernate_entities_deletes_total{application_name=\"$application\", application_instanceId=~\"$instance\"}[1m])",
     "legendFormat": "deletes",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hibernate Optimistic Locking Failures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "increase(hibernate_optimistic_failures_total{application_name=\"$application\", application_instanceId=~\"$instance\"}[1m])",
     "legendFormat": "optimistic failures",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "hikaricp_connections_active{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "active",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "hikaricp_connections_idle{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "idle",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "hikaricp_connections_max{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "max",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}