{
 "title": "Test",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "query": "label_values(application)" },
   { "name": "job", "query": "label_values(job)" },
   { "name": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Running applications",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(process_uptime_seconds) by (application) or (1-absent(process_uptime_seconds))"
    }
   ]
  },
  {
   "title": "application1",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(process_uptime_seconds{application=\"$application\"}) by (application) or (1-absent(process_uptime_seconds{application=\"$application\"}))"
    }
   ]
  },
  {
   "title": "Application Status",
   "type": "singlestat",
   "description": "This method shows if the application is running or not",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(process_uptime_seconds) or (1-absent(process_uptime_seconds))"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "singlestat",
   "description": "This method shows if the application is running or not",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(process_uptime_seconds) or (1-absent(process_uptime_seconds))"
    }
   ]
  }
 ]
}